apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-model-deployment
  labels:
    app: ml-model
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ml-model
  template:
    metadata:
      labels:
        app: ml-model
    spec:
      containers:
        - name: ml-model
          image: acrterraformsepsisstreaming.azurecr.io/your-image-name:latest
          ports:
            - containerPort: 5000
          env:
            - name: ENV
              value: "production" # Optional: Set environment variables
