channels:
- conda-forge
dependencies:
- python=3.11.5
- pip<=23.3.1
- pip:
  - mlflow==2.15.1
  - cloudpickle==2.2.1
  - numpy==1.23.5
  - psutil==6.0.0
  - scikit-learn==1.4.2
  - scipy==1.13.0
name: mlflow-env
